### ISSUE TITLE
We shouldn't prompt competitors for a uniquename if the person with their name is ... themselves

### ISSUE THREAD

**Issue by jfly** [jfly/ccm#124]
I think this is as simple as tweaking needsUniqueName in client/competitionRegistration.js. @jbcm627 , can you take this on?

**Comment by jfly** [comment]
Furthermore, it might be best if we don't allow competitors to change their uniqueName for a competition, as we copy it into all our Results.

**Comment by jbcm627** [comment]
What case do you have in mind here?  I don't think we want people having multiple accounts or registrations, right?

And I don't think people are able to change their registration at all after the registration close date (which should be before the competition), right?  uniqueName is part of registration.
