### ISSUE TITLE
Error when trying to clear name in user profile

### ISSUE THREAD

**Issue by jfly** [jfly/ccm#127]
If i delete the name field and hit save, I see "MongoError: have conflicting mods in update [409]" in my console. @jbcm627, do you have any time to take a look into this? It seems reasonable to me to not allow people to clear their names after they've been set.

**Comment by jbcm627** [comment]
Hm, I see no errors when I try this on staging.live.jflei.com, or locally.  What are conflicting mods?  Should I meteor reset to reproduce this?

**Comment by jfly** [comment]
Strange, perhaps I broke this locally. I will dig into this in a bit.
