### ISSUE TITLE
Schedule Editor

### ISSUE THREAD

**Issue by FatBoyXPC** [jfly/ccm#139]
When multiple days are added to the schedule, it makes all of the unscheduled events at the top incredibly hard to read. Even with only a one day schedule, it's still fairly difficult to read. There is some dead space on the left side of the page, underneath the start date and associated fields. We could possibly put a header "Unscheduled Rounds" and list them in a scrollable area under that? Unfortunately, this wouldn't work out great for the mobile view. This could be fixed by enabling the same click to edit round like what exists for a scheduled round. I imagine dragging and dropping on a phone isn't too optimal, anyway.

**Comment by jfly** [comment]
Haha, dragging and dropping doesn't even work on a phone right now =). I don't think we need to worry about going out of our wayt to design the manage/* views for mobile.

I do like the idea of putting the unscheduled rounds on the left part of the page
