### ISSUE TITLE
IE 11 doesn't seem to work =(

### ISSUE THREAD

**Issue by jfly** [jfly/ccm#65]
Looks like a problem with autoform, actually. Unfortunately, we do need to get this working for Phase 1, or else competitors won't necessarily be able to register for competitions.

**Comment by jbcm627** [comment]
Reopening for a different reason.  [insert griping and generic snarky comment about cross-browser compatibility].

![image](https://cloud.githubusercontent.com/assets/964048/5752890/ed73edaa-9c4c-11e4-8d6e-cd1e9b6d4868.png)

**Comment by jbcm627** [comment]
Fixed this up in 73e2e190543915337c19c8bdcecce4efb46c8fdc, closing again.
